"""empty message

Revision ID: 032c7a06150a
Revises: d6579216e621
Create Date: 2020-06-21 15:03:11.116018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '032c7a06150a'
down_revision = 'd6579216e621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('benefits', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benefits', sa.Column('status', mysql.VARCHAR(length=8), nullable=True))
    # ### end Alembic commands ###
