"""empty message

Revision ID: 1a9939b485ec
Revises: 34455b640935
Create Date: 2020-06-22 11:31:59.659802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9939b485ec'
down_revision = '34455b640935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benefits', sa.Column('slug', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('benefits', 'slug')
    # ### end Alembic commands ###
