"""empty message

Revision ID: 34455b640935
Revises: 032c7a06150a
Create Date: 2020-06-22 10:22:02.097836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34455b640935'
down_revision = '032c7a06150a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'icon')
    # ### end Alembic commands ###
