"""empty message

Revision ID: dd735603434d
Revises: 
Create Date: 2020-06-23 11:21:03.804931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd735603434d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('icon', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('whatsapp', sa.String(length=11), nullable=True),
    sa.Column('password', sa.String(length=400), nullable=False),
    sa.Column('email', sa.String(length=25), nullable=False),
    sa.Column('thumb', sa.String(length=25), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('benefits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.Text(length=800), nullable=False),
    sa.Column('moderation', sa.Integer(), nullable=True),
    sa.Column('thumbone', sa.String(length=50), nullable=False),
    sa.Column('thumbtwo', sa.String(length=50), nullable=False),
    sa.Column('thumbthree', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=True),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('benefits')
    op.drop_table('users')
    op.drop_table('states')
    op.drop_table('categories')
    # ### end Alembic commands ###
